import {db,gameRef,doc,getDoc,setDoc,updateDoc,onSnapshot,collection,getDocs,serverTimestamp,writeBatch} from './firebase.js';
import {qs,esc,norm,randomLetter,DEFAULT_CATEGORIES} from './common.js';
let game={status:'lobby',round:0};let teams=[];let scoresDraft={};
await setDoc(gameRef,{status:'lobby',round:0,createdAt:serverTimestamp()},{merge:true});
onSnapshot(gameRef,s=>{if(s.exists())game=s.data();renderState()});
onSnapshot(collection(db,'games',gameRef.id,'teams'),s=>{teams=s.docs.map(d=>({id:d.id,...d.data()}));renderTeams()});
function renderState(){qs('#round').textContent=game.round||0;qs('#letter').textContent=game.letter||'-';qs('#status').textContent=game.status||'lobby';qs('#review').disabled=game.status!=='stopped';if(game.status==='review')buildReview();}
function renderTeams(){qs('#teams').innerHTML=teams.length?teams.sort((a,b)=>(b.score||0)-(a.score||0)).map(t=>`<div class="team">${esc(t.name)} <span class="muted">• ${t.score||0} pts</span></div>`).join(''):'<div class="muted">Nenhuma equipe conectada.</div>';if(game.status==='review')buildReview()}
qs('#start').addEventListener('click',async()=>{const cats=qs('#categories').value.split('\n').map(x=>x.trim()).filter(Boolean).slice(0,12);const duration=Math.max(30,Math.min(300,Number(qs('#duration').value)||90));const end=new Date(Date.now()+duration*1000);await updateDoc(gameRef,{status:'playing',round:(game.round||0)+1,letter:randomLetter(),categories:cats.length?cats:DEFAULT_CATEGORIES,startedAt:serverTimestamp(),endsAt:end,stopAt:null,stopById:null,stopByName:null});});
qs('#review').addEventListener('click',()=>updateDoc(gameRef,{status:'review'}));
qs('#reset').addEventListener('click',async()=>{if(!confirm('Zerar placar e respostas de todas as equipes?'))return;const batch=writeBatch(db);teams.forEach(t=>batch.set(doc(db,'games',gameRef.id,'teams',t.id),{score:0,answers:{},round:0},{merge:true}));batch.set(gameRef,{status:'lobby',round:0,letter:null,categories:DEFAULT_CATEGORIES,stopByName:null},{merge:true});await batch.commit();});
function suggestion(answer,cat){const a=norm(answer);if(!a||!a.startsWith(norm(game.letter||'')))return 0;const same=teams.filter(t=>norm((t.answers||{})[cat])===a).length;return same>1?5:10}
function buildReview(){const area=qs('#reviewArea');const cats=game.categories||[];scoresDraft={};let html='';cats.forEach(cat=>{html+=`<div class="category-card" style="margin-bottom:12px"><h3>${esc(cat)}</h3>`;teams.forEach(t=>{const ans=(t.round===game.round&&t.answers?.[cat])||'';const sug=suggestion(ans,cat);scoresDraft[`${t.id}|${cat}`]=sug;html+=`<div class="review-row"><b>${esc(t.name)}</b><div>${esc(ans)||'<span class="muted">— vazio —</span>'}</div><select class="scoreSel" data-team="${t.id}" data-cat="${esc(cat)}"><option value="10" ${sug===10?'selected':''}>10 — válida única</option><option value="5" ${sug===5?'selected':''}>5 — repetida</option><option value="0" ${sug===0?'selected':''}>0 — inválida</option></select></div>`});html+='</div>'});area.innerHTML=html;document.querySelectorAll('.scoreSel').forEach(s=>s.addEventListener('change',()=>scoresDraft[`${s.dataset.team}|${s.dataset.cat}`]=Number(s.value)));qs('#finishReview').hidden=false;}
qs('#finishReview').addEventListener('click',async()=>{const batch=writeBatch(db);teams.forEach(t=>{let add=0;(game.categories||[]).forEach(c=>add+=scoresDraft[`${t.id}|${c}`]||0);batch.set(doc(db,'games',gameRef.id,'teams',t.id),{score:(t.score||0)+add},{merge:true})});batch.set(gameRef,{status:'lobby',letter:null,stopByName:null},{merge:true});await batch.commit();qs('#finishReview').hidden=true;qs('#reviewArea').innerHTML='';});
