import {db,gameRef,doc,setDoc,updateDoc,onSnapshot,collection,serverTimestamp,runTransaction} from './firebase.js';
import {qs,esc,getTeamId,fmtTime} from './common.js';
const teamId=getTeamId();let game=null,team=null,timerInt=null,lastAnswers={};
const join=qs('#join'),waiting=qs('#waiting'),gameEl=qs('#game'),stopped=qs('#stopped');
function setStatus(s){qs('#statusText').textContent=s;qs('#dot').className='dot '+(s==='Jogando'?'live':s==='STOP'?'stop':'')}
async function joinGame(name){team={id:teamId,name:name.trim()};await setDoc(doc(db,'games',gameRef.id,'teams',teamId),{name:team.name,score:0,joinedAt:serverTimestamp(),answers:{},round:0},{merge:true});sessionStorage.setItem('texStopTeamName',team.name);render()}
qs('#joinForm').addEventListener('submit',e=>{e.preventDefault();joinGame(qs('#teamName').value)});
const saved=sessionStorage.getItem('texStopTeamName');if(saved){team={id:teamId,name:saved};}
onSnapshot(collection(db,'games',gameRef.id,'teams'),snap=>{const teams=snap.docs.map(d=>({id:d.id,...d.data()}));const mine=teams.find(t=>t.id===teamId);if(mine)team=mine;qs('#teams').innerHTML=teams.map(t=>`<div class="team">${esc(t.name)}</div>`).join('');render()});
onSnapshot(gameRef,snap=>{game=snap.exists()?snap.data():null;render();});
function render(){if(!team){join.hidden=false;waiting.hidden=gameEl.hidden=stopped.hidden=true;return}join.hidden=true;qs('#hello').textContent=`Equipe: ${team.name}`;if(!game||game.status==='lobby'||game.status==='review'||game.status==='finished'){waiting.hidden=false;gameEl.hidden=stopped.hidden=true;setStatus(game?.status==='review'?'Correção':'Aguardando');return}if(game.status==='playing'){waiting.hidden=true;stopped.hidden=true;gameEl.hidden=false;setStatus('Jogando');renderRound();return}if(game.status==='stopped'){waiting.hidden=true;gameEl.hidden=true;stopped.hidden=false;setStatus('STOP');qs('#stopMessage').textContent=`${game.stopByName||'Uma equipe'} pediu STOP.`;showFlash(game.stopByName||'');}}
function renderRound(){qs('#letter').textContent=game.letter||'?';const cats=game.categories||[];const currentRound=game.round||1;if(!qs('#answerList').dataset.round||qs('#answerList').dataset.round!=currentRound){qs('#answerList').dataset.round=currentRound;lastAnswers=(team?.round===currentRound&&team.answers)||{};qs('#answerList').innerHTML=cats.map((c,i)=>`<div class="answer-row"><b>${esc(c)}</b><input class="answer" data-cat="${esc(c)}" maxlength="45" autocomplete="off" value="${esc(lastAnswers[c]||'')}"></div>`).join('');document.querySelectorAll('.answer').forEach(inp=>inp.addEventListener('input',debounceSave));}
clearInterval(timerInt);tick();timerInt=setInterval(tick,250);}
function tick(){if(!game?.endsAt){qs('#timer').textContent='--:--';return}const end=game.endsAt.toMillis?game.endsAt.toMillis():game.endsAt;const ms=end-Date.now();qs('#timer').textContent=fmtTime(ms);if(ms<=0&&game.status==='playing')requestStop('TEMPO');}
let saveTimer;function debounceSave(){clearTimeout(saveTimer);saveTimer=setTimeout(saveAnswers,180)}
async function saveAnswers(){if(!game||game.status!=='playing')return;const answers={};document.querySelectorAll('.answer').forEach(i=>answers[i.dataset.cat]=i.value.trim());lastAnswers=answers;await updateDoc(doc(db,'games',gameRef.id,'teams',teamId),{answers,round:game.round,updatedAt:serverTimestamp()}).catch(()=>{});}
qs('#stopBtn').addEventListener('click',async()=>{await saveAnswers();await requestStop(team.name)});
async function requestStop(by){try{await runTransaction(db,async tx=>{const snap=await tx.get(gameRef);if(!snap.exists())return;const d=snap.data();if(d.status!=='playing')return;tx.update(gameRef,{status:'stopped',stopById:by==='TEMPO'?null:teamId,stopByName:by==='TEMPO'?'TEMPO ESGOTADO':by,stopAt:serverTimestamp()});});}catch(e){console.error(e)}}
let flashedRound=0;function showFlash(who){if(!game||flashedRound===game.round)return;flashedRound=game.round;qs('#flashWho').textContent=who;qs('#flash').classList.add('show');setTimeout(()=>qs('#flash').classList.remove('show'),1600)}
